### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by pgzhong** [pgzhong/rsmpi-low#1]
- [X] types
- [ ] ch3_point_to_point_communication
- [ ] ch5_datatypes
- [ ] ch6_collective_communication
- [ ] ch7_contexts
- [ ] ch8_topologies
- [ ] ch9_env
- [ ] ch10_info
- [ ] ch11_process
- [ ] ch12_one_sided_communications
- [ ] ch13_external
- [ ] ch14_io
- [ ] ch15_tool
- [ ] ch19_binding
